In [0]:
import pandas as pd
import numpy as np
import matplotlib as plt
import dateutil as dt

### **Load DataSet**

In [0]:
url = 'https://raw.githubusercontent.com/EngenhariaDeComputacaoReinaldo/miniCursoPandas/master/phone_data.csv'
dfCall = pd.read_csv(url, index_col=0)

In [0]:
dfCall.head(20)

                     date  duration  item    month    network network_type
index
0     2014-10-15 06:58:00    34.429  data  2014-11       data         data
1     2014-10-15 06:58:00    13.000  call  2014-11   Vodafone       mobile
2     2014-10-15 14:46:00    23.000  call  2014-11     Meteor       mobile
3     2014-10-15 14:48:00     4.000  call  2014-11      Tesco       mobile
4     2014-10-15 17:27:00     4.000  call  2014-11      Tesco       mobile
5     2014-10-15 18:55:00     4.000  call  2014-11      Tesco       mobile
6     2014-10-16 06:58:00    34.429  data  2014-11       data         data
7     2014-10-16 15:01:00   602.000  call  2014-11      Three       mobile
8     2014-10-16 15:12:00  1050.000  call  2014-11      Three       mobile
9     2014-10-16 15:30:00    19.000  call  2014-11  voicemail    voicemail
10    2014-10-16 16:21:00  1183.000  call  2014-11      Three       mobile
11    2014-10-16 22:18:00     1.000   sms  2014-11     Meteor       mobile
12    2014-10-16 22:21:00     1.000   sms  2014-11     Meteor       mobile
13    2014-10-17 06:58:00    34.429  data  2014-11       data         data
14    2014-10-17 10:53:00     1.000   sms  2014-11      Tesco       mobile
15    2014-10-17 11:19:00     1.000   sms  2014-11      Tesco       mobile
16    2014-10-17 11:20:00     1.000   sms  2014-11     Meteor       mobile
17    2014-10-17 17:22:00     1.000   sms  2014-11   Vodafone       mobile
18    2014-10-17 17:23:00     1.000   sms  2014-11   Vodafone       mobile
19    2014-10-17 17:26:00    92.000  call  2014-11      Three       mobile

### **Convertendo a Data de String para DateTime**

In [0]:
dfCall['date'] = dfCall['date'].apply(dt.parser.parse, dayfirst=True)

In [0]:
dfCall.head(5)

                     date  duration  item    month   network network_type
index
0     2014-10-15 06:58:00    34.429  data  2014-11      data         data
1     2014-10-15 06:58:00    13.000  call  2014-11  Vodafone       mobile
2     2014-10-15 14:46:00    23.000  call  2014-11    Meteor       mobile
3     2014-10-15 14:48:00     4.000  call  2014-11     Tesco       mobile
4     2014-10-15 17:27:00     4.000  call  2014-11     Tesco       mobile

### **Quantidade de Linhas no DataSet**

In [0]:
dfCall.count()

date            830
duration        830
item            830
month           830
network         830
network_type    830
dtype: int64

### **Qual foi o maior tempo ligação**

In [0]:
dfCall['duration'].max()

10528.0

### Quantos segundos de chamadas de Calls foram armazenadas no total?

In [0]:
dfCall['duration'][dfCall['item'] == 'call'].sum()

92321.0

### **Quantidades de chamadas em cada mes**

In [0]:
dfCall['month'].value_counts()

2014-11    230
2015-01    205
2014-12    157
2015-02    137
2015-03    101
Name: month, dtype: int64

## **Agrupamento**
GroupBy essencialmente divide o dado dentro de diferentes grupos, dependendo da variável de sua escolha. Por exemplo a expressão dfCall.groupby('month') ira dividir nosso DataFrame atual em meses.

A função groupby() retorna um objeto groupby, mas, essencialmete descreve como as linhas de um dataSet original podem ser divididas.

Seus Grupos essencialmente se tornam índices de subgrupos de dados

### **retornar os indices dos agrupamentos**

In [0]:
dfCall.groupby(['month']).groups.keys()

dict_keys(['2014-11', '2014-12', '2015-01', '2015-02', '2015-03'])

### **retorna  a primeira entrada para cada mês**

In [0]:
dfCall.groupby('month').first()

                       date  duration  item   network network_type
month
2014-11 2014-10-15 06:58:00    34.429  data      data         data
2014-12 2014-11-13 06:58:00    34.429  data      data         data
2015-01 2014-12-13 06:58:00    34.429  data      data         data
2015-02 2015-01-13 06:58:00    34.429  data      data         data
2015-03 2015-02-12 20:15:00    69.000  call  landline     landline

### **Soma do tempo de ligações por mês**

In [0]:
dfCall.groupby('month')['duration'].sum()

month
2014-11    26639.441
2014-12    14641.870
2015-01    18223.299
2015-02    15522.299
2015-03    22750.441
Name: duration, dtype: float64

### **Quantidade de Datas por Mês**

In [0]:
dfCall.groupby('month')['date'].count()

month
2014-11    230
2014-12    157
2015-01    205
2015-02    137
2015-03    101
Name: date, dtype: int64

### **Soma do tempo de duração somentes das ligações do tipo Call em cada rede (network)**

In [0]:
dfCall[dfCall['item'] == 'call'].head(10)

                     date  duration  item    month    network network_type
index
1     2014-10-15 06:58:00      13.0  call  2014-11   Vodafone       mobile
2     2014-10-15 14:46:00      23.0  call  2014-11     Meteor       mobile
3     2014-10-15 14:48:00       4.0  call  2014-11      Tesco       mobile
4     2014-10-15 17:27:00       4.0  call  2014-11      Tesco       mobile
5     2014-10-15 18:55:00       4.0  call  2014-11      Tesco       mobile
7     2014-10-16 15:01:00     602.0  call  2014-11      Three       mobile
8     2014-10-16 15:12:00    1050.0  call  2014-11      Three       mobile
9     2014-10-16 15:30:00      19.0  call  2014-11  voicemail    voicemail
10    2014-10-16 16:21:00    1183.0  call  2014-11      Three       mobile
19    2014-10-17 17:26:00      92.0  call  2014-11      Three       mobile

In [0]:
dfCall[dfCall['item'] == 'call'].groupby('network')['duration'].sum()

network
Meteor        7200.0
Tesco        13828.0
Three        36464.0
Vodafone     14621.0
landline     18433.0
voicemail     1775.0
Name: duration, dtype: float64

### **Qual a quantidade de chamadas, textos e dados são enviados por mes, dividos por rede?**

In [0]:
dfCall.groupby(['month', 'network_type'])['date'].count()

month    network_type
2014-11  data             29
         landline          5
         mobile          189
         special           1
         voicemail         6
2014-12  data             30
         landline          7
         mobile          108
         voicemail         8
         world             4
2015-01  data             31
         landline         11
         mobile          160
         voicemail         3
2015-02  data             31
         landline          8
         mobile           90
         special           2
         voicemail         6
2015-03  data             29
         landline         11
         mobile           54
         voicemail         4
         world             3
Name: date, dtype: int64

Agregações permitem que várias estátisticas sejam calculdas por um grupo em um calculo apenas. 
Instruções de agregaçaõ são fornecidas na forma de dicionarios ou listas em Python. No caso de dicionários, as chaves são usadas para especificar as colunas na qual a operação será realizada e os valores especificam a função a ser aplicada.

In [0]:
dfCall.groupby(['month', 'item']).agg(
    {
         'duration':"sum",    # Soma duração da ligação por grupo
         'network_type': "count",  # Obtém a contagem de redes (quantidade de registros)
         'date': "first"  # Obtem a primeira data por grupo
    }
)

               duration  network_type                date
month   item
2014-11 call  25547.000           107 2014-10-15 06:58:00
        data    998.441            29 2014-10-15 06:58:00
        sms      94.000            94 2014-10-16 22:18:00
2014-12 call  13561.000            79 2014-11-14 17:24:00
        data   1032.870            30 2014-11-13 06:58:00
        sms      48.000            48 2014-11-14 17:28:00
2015-01 call  17070.000            88 2014-12-15 20:03:00
        data   1067.299            31 2014-12-13 06:58:00
        sms      86.000            86 2014-12-15 19:56:00
2015-02 call  14416.000            67 2015-01-15 10:36:00
        data   1067.299            31 2015-01-13 06:58:00
        sms      39.000            39 2015-01-15 12:23:00
2015-03 call  21727.000            47 2015-02-12 20:15:00
        data    998.441            29 2015-02-13 06:58:00
        sms      25.000            25 2015-02-19 18:46:00

### **Definindo a função de agregação antes**

In [0]:
aggCustom = {
    # find the min, max, and sum of the duration column
    'duration': [min, max, sum],
     # find the number of network type entries
    'network_type': "count",
    # min, first, and number of unique dates per group
    'date': [min, 'first', 'nunique']
}

### **Aplicando sobre  DataSet**

In [0]:
# Group the data frame by month and item and extract a number of stats from each group
dfCall.groupby(
    ['month', 'item']
).agg(aggCustom)

             duration                       network_type                date  \
                  min        max        sum        count                 min
month   item
2014-11 call    1.000   1940.000  25547.000          107 2014-10-15 06:58:00
        data   34.429     34.429    998.441           29 2014-10-15 06:58:00
        sms     1.000      1.000     94.000           94 2014-10-16 22:18:00
2014-12 call    2.000   2120.000  13561.000           79 2014-11-14 17:24:00
        data   34.429     34.429   1032.870           30 2014-11-13 06:58:00
        sms     1.000      1.000     48.000           48 2014-11-14 17:28:00
2015-01 call    2.000   1859.000  17070.000           88 2014-12-15 20:03:00
        data   34.429     34.429   1067.299           31 2014-12-13 06:58:00
        sms     1.000      1.000     86.000           86 2014-12-15 19:56:00
2015-02 call    1.000   1863.000  14416.000           67 2015-01-15 10:36:00
        data   34.429     34.429   1067.299           31 2015-01-13 06:58:00
        sms     1.000      1.000     39.000           39 2015-01-15 12:23:00
2015-03 call    2.000  10528.000  21727.000           47 2015-02-12 20:15:00
        data   34.429     34.429    998.441           29 2015-02-13 06:58:00
        sms     1.000      1.000     25.000           25 2015-02-19 18:46:00


                           first nunique
month   item
2014-11 call 2014-10-15 06:58:00     104
        data 2014-10-15 06:58:00      29
        sms  2014-10-16 22:18:00      79
2014-12 call 2014-11-14 17:24:00      76
        data 2014-11-13 06:58:00      30
        sms  2014-11-14 17:28:00      41
2015-01 call 2014-12-15 20:03:00      84
        data 2014-12-13 06:58:00      31
        sms  2014-12-15 19:56:00      58
2015-02 call 2015-01-15 10:36:00      67
        data 2015-01-13 06:58:00      31
        sms  2015-01-15 12:23:00      27
2015-03 call 2015-02-12 20:15:00      47
        data 2015-02-13 06:58:00      29
        sms  2015-02-19 18:46:00      17